import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'

import Footer from '@/components/Footer'


export default function Home() {
  return (
    <>
      <Head>
        <title>Invest in Innersight</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.signUp}>
          <div className={styles.box}></div>

        </div>
        <div className={styles.keyFeatures}>

        </div>
        <div className={styles.press}>

        </div>
        <Footer />
      </main>
    </>
  )
}
